#pragma once
struct StrModul;
struct Vec3;
struct Zusi;
struct Dateiverknuepfung;
struct Signal;
struct Ereignis;
struct Fahrplan;
struct FahrstrStart;
struct FahrstrWeiche;
struct NachfolgerSelbesModul;
struct UTM;
struct StreckenelementRichtungsInfo;
struct FahrstrZiel;
struct Strecke;
struct ReferenzElement;
struct StrElement;
struct NachfolgerAnderesModul;
struct Fahrstrasse;
