#pragma once
struct StrModul;
struct Vec3;
struct Zusi;
struct Dateiverknuepfung;
struct Signal;
struct Ereignis;
struct Fahrplan;
struct NachfolgerSelbesModul;
struct UTM;
struct StreckenelementRichtungsInfo;
struct Strecke;
struct ReferenzElement;
struct StrElement;
struct NachfolgerAnderesModul;
