#pragma once
struct NachfolgerAnderesModul;
struct ReferenzElement;
struct NachfolgerSelbesModul;
struct Strecke;
struct StreckenelementRichtungsInfo;
struct StrModul;
struct Vec3;
struct Zusi;
struct Signal;
struct Dateiverknuepfung;
struct UTM;
struct StrElement;
struct Fahrplan;
